# Generated by Django 2.1.5 on 2019-02-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_auto_20190202_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='item_name',
            new_name='text',
        ),
    ]
